"use client"

import Box from "@mui/material/Box"
import Button from "@mui/material/Button"
import Card from "@mui/material/Card"
import CardContent from "@mui/material/CardContent"
import Typography from "@mui/material/Typography"
import { FileText, Lock, Download, Check } from "lucide-react"
import type { Gender } from "@/lib/fitness-context"

interface PdfPreviewProps {
  isUnlocked: boolean
  userData: {
    firstName: string
    lastName: string
    age: number
    height: number
    weight: number
    gender: Gender
    activityLevel: string
    activityType: string
  }
  onGeneratePdf: () => void
  bmi: number
  bmiCategory: string
  idealRange: { min: number; max: number }
}

export function PdfPreview({
  isUnlocked,
  userData,
  onGeneratePdf,
  bmi,
  bmiCategory,
  idealRange,
}: PdfPreviewProps) {
  const handleDownload = async () => {
    const { jsPDF } = await import("jspdf")
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })

    const pageW = doc.internal.pageSize.getWidth()
    const margin = 20
    const contentW = pageW - margin * 2
    let y = margin

    // Header bar
    doc.setFillColor(37, 99, 235)
    doc.rect(0, 0, pageW, 40, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(22)
    doc.setFont("helvetica", "bold")
    doc.text("ebook", margin, 22)
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    doc.text("Personal Fitness Report", margin, 32)
    doc.setFontSize(10)
    doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), pageW - margin, 32, { align: "right" })

    y = 55

    // Section helper
    const sectionTitle = (title: string) => {
      doc.setFillColor(243, 244, 246)
      doc.roundedRect(margin, y - 5, contentW, 10, 2, 2, "F")
      doc.setTextColor(37, 99, 235)
      doc.setFontSize(11)
      doc.setFont("helvetica", "bold")
      doc.text(title, margin + 4, y + 2)
      y += 12
    }

    const row = (label: string, value: string) => {
      doc.setTextColor(100, 116, 139)
      doc.setFontSize(10)
      doc.setFont("helvetica", "normal")
      doc.text(label, margin + 4, y)
      doc.setTextColor(15, 23, 42)
      doc.setFont("helvetica", "bold")
      doc.text(value, margin + 60, y)
      y += 8
    }

    // Personal Information
    sectionTitle("Personal Information")
    row("Full Name", `${userData.firstName} ${userData.lastName}`)
    row("Gender", userData.gender.charAt(0).toUpperCase() + userData.gender.slice(1))
    row("Age", `${userData.age} years`)
    y += 4

    // Body Metrics
    sectionTitle("Body Metrics")
    row("Height", `${userData.height} cm`)
    row("Weight", `${userData.weight} kg`)
    row("BMI", `${bmi} — ${bmiCategory}`)
    row("Ideal Weight Range", `${idealRange.min} – ${idealRange.max} kg`)
    y += 4

    // Activity Profile
    sectionTitle("Activity Profile")
    row("Activity Level", userData.activityLevel.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()))
    if (userData.activityType) {
      row("Activity Type", userData.activityType.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()))
    }
    y += 8

    // Footer
    doc.setDrawColor(229, 231, 235)
    doc.line(margin, y, pageW - margin, y)
    y += 6
    doc.setTextColor(156, 163, 175)
    doc.setFontSize(9)
    doc.setFont("helvetica", "italic")
    doc.text("Generated by ebook — transform your body, unlock your potential.", pageW / 2, y, { align: "center" })

    doc.save(`ebook_Report_${userData.firstName}_${userData.lastName}.pdf`)
  }

  return (
    <Card sx={{ border: "1px solid rgba(255,255,255,0.1)", boxShadow: "0 20px 60px rgba(0,0,0,0.4)", position: "relative", overflow: "hidden" }}>
      {!isUnlocked && (
        <Box sx={{ position: "absolute", inset: 0, zIndex: 10, display: "flex", alignItems: "center", justifyContent: "center", bgcolor: "rgba(15,23,32,0.8)", backdropFilter: "blur(6px)" }}>
          <Box sx={{ textAlign: "center", p: 3 }}>
            <Box sx={{ display: "inline-flex", alignItems: "center", justifyContent: "center", width: 64, height: 64, borderRadius: "50%", bgcolor: "rgba(33,150,243,0.1)", mb: 2 }}>
              <Lock size={32} color="#2196f3" />
            </Box>
            <Typography variant="h6" sx={{ fontWeight: 700, mb: 1 }}>Unlock Your Report</Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 3, maxWidth: 280 }}>
              Get your detailed fitness analysis and personalized recommendations
            </Typography>
            <Button variant="contained" startIcon={<FileText size={16} />} onClick={onGeneratePdf}>
              Generate PDF — $4.99
            </Button>
          </Box>
        </Box>
      )}

      <CardContent sx={{ p: 3 }}>
        {/* Header row */}
        <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", mb: 2 }}>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, display: "flex", alignItems: "center", gap: 1 }}>
              <FileText size={20} color="#2196f3" /> Your Fitness Report
            </Typography>
            <Typography variant="body2" color="text.secondary">Personal details and body metrics summary</Typography>
          </Box>
          {isUnlocked && (
            <Box sx={{ display: "inline-flex", alignItems: "center", gap: 0.75, px: 1.5, py: 0.5, borderRadius: 99, bgcolor: "rgba(76,175,80,0.1)", color: "#4caf50" }}>
              <Check size={14} />
              <Typography variant="caption" sx={{ fontWeight: 600 }}>Unlocked</Typography>
            </Box>
          )}
        </Box>

        {/* Content (blurred when locked) */}
        <Box sx={{ borderRadius: 2, border: "1px solid rgba(255,255,255,0.08)", bgcolor: "rgba(255,255,255,0.03)", p: 3, filter: isUnlocked ? "none" : "blur(6px)", userSelect: isUnlocked ? "auto" : "none" }}>
          <Box sx={{ display: "flex", alignItems: "center", gap: 2, pb: 2, mb: 2, borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
            <Box sx={{ width: 48, height: 48, borderRadius: 2, bgcolor: "rgba(33,150,243,0.1)", display: "flex", alignItems: "center", justifyContent: "center" }}>
              <FileText size={24} color="#2196f3" />
            </Box>
            <Box>
              <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>ebook Report</Typography>
              <Typography variant="body2" color="text.secondary">{userData.firstName} {userData.lastName}</Typography>
            </Box>
          </Box>

          <Box sx={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 2 }}>
            {[
              { label: "Age", value: `${userData.age} years` },
              { label: "Gender", value: userData.gender },
              { label: "Height", value: `${userData.height} cm` },
              { label: "Weight", value: `${userData.weight} kg` },
              { label: "BMI", value: `${bmi} (${bmiCategory})` },
              { label: "Ideal Range", value: `${idealRange.min}–${idealRange.max} kg` },
            ].map(({ label, value }) => (
              <Box key={label}>
                <Typography variant="caption" color="text.secondary">{label}</Typography>
                <Typography variant="body2" sx={{ fontWeight: 600, textTransform: "capitalize" }}>{value}</Typography>
              </Box>
            ))}
          </Box>
        </Box>

        {isUnlocked && (
          <Button variant="contained" fullWidth startIcon={<Download size={16} />} onClick={handleDownload} sx={{ mt: 2 }}>
            Download PDF
          </Button>
        )}
      </CardContent>
    </Card>
  )
}
